### ISSUE TITLE
Menu Filter

### ISSUE THREAD

**Issue by Keko-94** [Muetze42/nova-menu#41] opened 2023-09-26 17:41 UTC
MainMenu.vue Line 30:
        <div className="menu-filter menu-filter-bottom" v-if="$page.props.menuAdvPosition && ['top', 'both'].includes($page.props.menuAdvPosition)">

should be ['bottom', 'both'] instead of top

MenuFilter::activate('both')->placeholder(__('Search menu')) broke all my translations, I don't know why :/

**Comment by Muetze42** [comment] 2023-09-28 12:53
So for me, the search runs as intended, even in Switzerland.

The data comes from the database and there is therefore a debounce of 300ms so that the server is not flooded.
 Is possibly that meant?

**Comment by Muetze42** [comment] 2023-10-02 10:35
Menu Filter Bottom was wrong. Is fixed in the current release.

Have You tested it without translation? 
`placeholder('Search menu')`

**Comment by Keko-94** [comment] 2023-10-11 08:00
Thanks for the fix.
Without translation it's working.

**Comment by Muetze42** [comment] 2023-10-11 08:13
Curious. So I use the package in several projects without problems. I can still try around a bit to see if I can recreate the error.

**Closed as completed** 2023-10-19 11:43 UTC
Labels: bug
